"""lines table

Revision ID: 71039e69c1f6
Revises: 
Create Date: 2019-11-06 13:52:05.007404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71039e69c1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flavor', sa.Text(), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('videoId', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_duration'), 'line', ['duration'], unique=False)
    op.create_index(op.f('ix_line_flavor'), 'line', ['flavor'], unique=False)
    op.create_index(op.f('ix_line_start'), 'line', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_start'), table_name='line')
    op.drop_index(op.f('ix_line_flavor'), table_name='line')
    op.drop_index(op.f('ix_line_duration'), table_name='line')
    op.drop_table('line')
    # ### end Alembic commands ###
